/**
 * Entitas Generated Classes for example
 *
 * do not edit this file
 */
module example {

  import Pool = entitas.Pool;
  import Entity = entitas.Entity;
  import Matcher = entitas.Matcher;
  import ISystem = entitas.ISystem;
  import IMatcher = entitas.IMatcher;
  import IComponent = entitas.IComponent;

  export enum CoreComponentIds {
    Acceleratable,
    Accelerating,
    Destroy,
    Move,
    Position,
    FinishLine,
    Resource,
    View,
    TotalComponents
  }


  export class AcceleratableComponent implements IComponent {
  }
  export class AcceleratingComponent implements IComponent {
  }
  export class DestroyComponent implements IComponent {
  }
  export class MoveComponent implements IComponent {
    public speed:number;
    public maxSpeed:number;
  }
  export class PositionComponent implements IComponent {
    public x:number;
    public y:number;
    public z:number;
  }
  export class FinishLineComponent implements IComponent {
  }
  export class ResourceComponent implements IComponent {
    public name:string;
  }
  export class ViewComponent implements IComponent {
    public sprite:Object;
  }


  export class Pools {
    
    static _allPools:Array<Pool>;
    
    static get allPools():Array<Pool> {
      if (Pools._allPools == null) {
        Pools._allPools = [Pools.pool];
      }
      return Pools._allPools;
    }
    
    static _pool:Pool;
    
    static get pool():Pool {
      if (Pools._pool == null) {
        Pools._pool = new Pool(CoreComponentIds, CoreComponentIds.TotalComponents);
        entitas.browser.VisualDebugging.init(Pools._pool);
      }
    
      return Pools._pool;
    }
  }
}