namespace {{ namespace }} 
/**
 * Entitas Generated Components and Extensions for {{ namespace }}
 *
 * do not edit this file
 */
 
using Entitas;
using System;
using System.Collections.Generic;


{% for component in components %}
public class {{ component.key }}Component : IComponent {
{% for field in component.value %}
    public {{ field | type }} {{ field | property }};
}
{% endfor %}{% endfor %}

